[package]
name = "calendar2discord"
version = "0.1.0"
edition = "2024"

[dependencies]
icalendar = { version = "0.17.3", default-features = false, features = ["parser"]}
reqwest = { version = "0.12.23", default-features = false }
